export const cardData = [

    {id: 1,
    title:"my favourite chords",
    desc:"poster",
    pic:"mfc_teaser",
    cat:[0,3],
    link:"mfc",
    row: 1,
    col: 1,
    rowt:1,
    colt:1},
    
    {id: 2,
    title:"rauschende wolken, schöne atome",
    desc:"research + publication + exhibition",
    pic:"rwsa_teaser",
    cat:[0,1,3],
    link:"rauschende-wolken",
    row: 3,
    col: 1,
    rowt:2,
    colt:2},
    
    {id:3,
    title:"female:pressure night",
    desc:"flyer",
    pic:"fp_teaser",
    cat:[0,3],
    link:"female-pressure",
    row: 2,
    col: 2,
    rowt:3,
    colt:1},
    
    {id:4,
    title:"lush3000",
    desc:"online game prototype",
    pic:"lush_teaser",
    cat:[0,1,4],
    link:"lush3000",
    row: 4,
    col: 2,
    rowt:4,
    colt:2},

    {id:5,
    title:"kirindou",
    desc:"logo",
    pic:"kirindou_teaser",
    cat:[0,1],
    link:"kirindou",
    row: 1,
    col: 3,
    rowt:5,
    colt:1,
    border: true},

    {id: 6,
    title:"empowerment",
    desc:"logo",
    pic:"empowerment_teaser",
    cat:[0,1],
    link:"empowerment",
    row: 3,
    col: 3,
    rowt:6,
    colt:2,},

    {id:7,
    title:"kirindou",
    desc:"logo",
    pic:"kirindou_teaser",
    cat:[0,1],
    link:"kirindou",
    row: 2,
    col: 4,
    rowt:7,
    colt:1,
    border:true},

    {id:7,
    title:"kirindou",
    desc:"logo",
    pic:"kirindou_teaser",
    cat:[0,1],
    link:"kirindou",
    row: 4,
    col: 4,
    rowt:8,
    colt:2,
    border: true,},
        
    ]